BEGIN;

CREATE TABLE IF NOT EXISTS schema_migrations (
    version varchar(32) PRIMARY KEY,
    description varchar(255) NOT NULL,
    applied_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE organizations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id bigint REFERENCES organizations(id),
    code varchar(64) NOT NULL UNIQUE,
    name varchar(255) NOT NULL,
    revision bigint NOT NULL DEFAULT 1 CHECK (revision > 0),
    enabled boolean NOT NULL DEFAULT true,
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE departments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES organizations(id),
    parent_department_id bigint REFERENCES departments(id),
    code varchar(64) NOT NULL,
    name varchar(255) NOT NULL,
    short_name varchar(128) NOT NULL DEFAULT '',
    sort_order integer NOT NULL DEFAULT 0,
    enabled boolean NOT NULL DEFAULT true,
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (organization_id, code)
);

CREATE INDEX idx_departments_parent ON departments(organization_id, parent_department_id, sort_order);

CREATE TABLE positions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES organizations(id),
    code varchar(64) NOT NULL,
    name varchar(255) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    UNIQUE (organization_id, code)
);

CREATE TABLE persons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES organizations(id),
    employee_number varchar(64) NOT NULL,
    display_name varchar(255) NOT NULL,
    avatar_resource_id varchar(255) NOT NULL DEFAULT '',
    work_phone varchar(64) NOT NULL DEFAULT '',
    extension_number varchar(32) NOT NULL DEFAULT '',
    work_email varchar(255) NOT NULL DEFAULT '',
    primary_department_id bigint REFERENCES departments(id),
    primary_position_id bigint REFERENCES positions(id),
    enabled boolean NOT NULL DEFAULT true,
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (organization_id, employee_number)
);

CREATE INDEX idx_persons_department ON persons(primary_department_id, enabled, display_name);
CREATE INDEX idx_persons_search_name ON persons(organization_id, display_name);

CREATE TABLE person_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id bigint NOT NULL REFERENCES persons(id) ON DELETE CASCADE,
    department_id bigint NOT NULL REFERENCES departments(id),
    position_id bigint REFERENCES positions(id),
    primary_assignment boolean NOT NULL DEFAULT false,
    sort_order integer NOT NULL DEFAULT 0,
    UNIQUE (person_id, department_id, position_id)
);

CREATE UNIQUE INDEX uq_person_primary_assignment
    ON person_assignments(person_id) WHERE primary_assignment;

CREATE TABLE user_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id bigint NOT NULL REFERENCES persons(id),
    login_name varchar(128) NOT NULL UNIQUE,
    password_hash bytea NOT NULL,
    password_algorithm varchar(32) NOT NULL,
    status smallint NOT NULL DEFAULT 0,
    failed_login_count integer NOT NULL DEFAULT 0,
    locked_until_utc timestamptz,
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at_utc timestamptz
);

CREATE TABLE organization_revisions (
    organization_id bigint PRIMARY KEY REFERENCES organizations(id),
    current_revision bigint NOT NULL CHECK (current_revision > 0),
    updated_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE organization_change_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES organizations(id),
    revision bigint NOT NULL,
    entity_type varchar(32) NOT NULL,
    entity_id bigint NOT NULL,
    change_type varchar(64) NOT NULL,
    changed_by_account_id bigint REFERENCES user_accounts(id),
    changed_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    change_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (organization_id, revision)
);

INSERT INTO schema_migrations(version, description)
VALUES ('001', 'organization and identity base schema')
ON CONFLICT (version) DO NOTHING;

GRANT CONNECT ON DATABASE orglink TO orglink_app;
GRANT USAGE ON SCHEMA public TO orglink_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO orglink_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO orglink_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO orglink_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO orglink_app;

COMMIT;

