BEGIN;

CREATE TABLE user_devices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
    device_uuid uuid NOT NULL,
    device_name varchar(255) NOT NULL,
    platform varchar(64) NOT NULL,
    public_key_fingerprint varchar(128) NOT NULL DEFAULT '',
    trusted boolean NOT NULL DEFAULT false,
    last_seen_at_utc timestamptz,
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (account_id, device_uuid)
);

CREATE TABLE login_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint REFERENCES user_accounts(id),
    device_id bigint REFERENCES user_devices(id),
    occurred_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_address inet,
    succeeded boolean NOT NULL,
    failure_code varchar(64) NOT NULL DEFAULT '',
    correlation_id uuid NOT NULL
);
CREATE INDEX idx_login_records_account_time ON login_records(account_id, occurred_at_utc DESC);

CREATE TABLE directory_visibility_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES organizations(id),
    subject_person_id bigint REFERENCES persons(id),
    subject_department_id bigint REFERENCES departments(id),
    visibility_scope smallint NOT NULL,
    target_department_ids bigint[] NOT NULL DEFAULT '{}',
    enabled boolean NOT NULL DEFAULT true,
    CHECK ((subject_person_id IS NOT NULL) <> (subject_department_id IS NOT NULL))
);

CREATE TABLE favorite_contacts (
    owner_person_id bigint NOT NULL REFERENCES persons(id) ON DELETE CASCADE,
    contact_person_id bigint NOT NULL REFERENCES persons(id) ON DELETE CASCADE,
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (owner_person_id, contact_person_id),
    CHECK (owner_person_id <> contact_person_id)
);

CREATE TABLE conversations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES organizations(id),
    conversation_type smallint NOT NULL,
    title varchar(255) NOT NULL DEFAULT '',
    active boolean NOT NULL DEFAULT true,
    created_by_person_id bigint NOT NULL REFERENCES persons(id),
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_message_sequence bigint NOT NULL DEFAULT 0 CHECK (last_message_sequence >= 0)
);
CREATE INDEX idx_conversations_org_activity ON conversations(organization_id, active, id);

-- 规范化参与者顺序并建立唯一约束，从数据库层阻止多节点并发创建重复单聊。
CREATE TABLE direct_conversations (
    conversation_id bigint PRIMARY KEY REFERENCES conversations(id) ON DELETE CASCADE,
    person_low_id bigint NOT NULL REFERENCES persons(id),
    person_high_id bigint NOT NULL REFERENCES persons(id),
    CHECK (person_low_id < person_high_id),
    UNIQUE (person_low_id, person_high_id)
);

CREATE TABLE conversation_members (
    conversation_id bigint NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    person_id bigint NOT NULL REFERENCES persons(id),
    joined_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at_utc timestamptz,
    last_delivered_sequence bigint NOT NULL DEFAULT 0,
    last_read_sequence bigint NOT NULL DEFAULT 0,
    muted boolean NOT NULL DEFAULT false,
    pinned boolean NOT NULL DEFAULT false,
    PRIMARY KEY (conversation_id, person_id),
    CHECK (last_read_sequence <= last_delivered_sequence)
);
CREATE INDEX idx_conversation_members_person ON conversation_members(person_id, left_at_utc, conversation_id);

CREATE TABLE chat_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id bigint NOT NULL UNIQUE REFERENCES conversations(id) ON DELETE CASCADE,
    owner_person_id bigint NOT NULL REFERENCES persons(id),
    group_type smallint NOT NULL,
    name varchar(255) NOT NULL,
    avatar_resource_id varchar(255) NOT NULL DEFAULT '',
    announcement text NOT NULL DEFAULT '',
    all_muted boolean NOT NULL DEFAULT false,
    active boolean NOT NULL DEFAULT true,
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE group_members (
    group_id bigint NOT NULL REFERENCES chat_groups(id) ON DELETE CASCADE,
    person_id bigint NOT NULL REFERENCES persons(id),
    member_role smallint NOT NULL DEFAULT 0,
    member_source varchar(32) NOT NULL DEFAULT 'manual',
    muted_until_utc timestamptz,
    joined_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (group_id, person_id)
);

CREATE TABLE messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server_message_id uuid NOT NULL UNIQUE,
    client_message_id uuid NOT NULL,
    conversation_id bigint NOT NULL REFERENCES conversations(id),
    sender_person_id bigint NOT NULL REFERENCES persons(id),
    sender_device_id bigint REFERENCES user_devices(id),
    sequence bigint NOT NULL CHECK (sequence > 0),
    message_type smallint NOT NULL,
    content_ciphertext bytea NOT NULL,
    content_search_text text,
    encryption_mode smallint NOT NULL DEFAULT 0,
    reply_to_message_id bigint REFERENCES messages(id),
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    recalled_at_utc timestamptz,
    UNIQUE (sender_device_id, client_message_id),
    UNIQUE (conversation_id, sequence)
);
CREATE INDEX idx_messages_conversation_page ON messages(conversation_id, sequence DESC);
CREATE INDEX idx_messages_created_at ON messages(created_at_utc);

CREATE TABLE message_receipts (
    message_id bigint NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    person_id bigint NOT NULL REFERENCES persons(id),
    device_id bigint REFERENCES user_devices(id),
    receipt_type smallint NOT NULL,
    received_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (message_id, person_id, receipt_type)
);
CREATE INDEX idx_message_receipts_person ON message_receipts(person_id, received_at_utc DESC);

CREATE TABLE file_assets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_uuid uuid NOT NULL UNIQUE,
    owner_person_id bigint NOT NULL REFERENCES persons(id),
    original_name varchar(512) NOT NULL,
    storage_key varchar(512) NOT NULL UNIQUE,
    media_type varchar(255) NOT NULL DEFAULT 'application/octet-stream',
    size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
    sm3_digest bytea NOT NULL,
    sha256_digest bytea,
    scan_status smallint NOT NULL DEFAULT 0,
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at_utc timestamptz,
    deleted_at_utc timestamptz
);
CREATE INDEX idx_file_assets_expiry ON file_assets(expires_at_utc) WHERE deleted_at_utc IS NULL;

CREATE TABLE file_transfer_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_uuid uuid NOT NULL UNIQUE,
    conversation_id bigint NOT NULL REFERENCES conversations(id),
    asset_id bigint REFERENCES file_assets(id),
    initiator_person_id bigint NOT NULL REFERENCES persons(id),
    transfer_direction smallint NOT NULL,
    transfer_mode smallint NOT NULL,
    status smallint NOT NULL,
    total_bytes bigint NOT NULL CHECK (total_bytes >= 0),
    transferred_bytes bigint NOT NULL DEFAULT 0 CHECK (transferred_bytes >= 0),
    checkpoint_chunk bigint NOT NULL DEFAULT 0,
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (transferred_bytes <= total_bytes)
);

CREATE TABLE file_chunks (
    task_id bigint NOT NULL REFERENCES file_transfer_tasks(id) ON DELETE CASCADE,
    chunk_index integer NOT NULL CHECK (chunk_index >= 0),
    offset_bytes bigint NOT NULL CHECK (offset_bytes >= 0),
    size_bytes integer NOT NULL CHECK (size_bytes > 0),
    sm3_digest bytea NOT NULL,
    uploaded boolean NOT NULL DEFAULT false,
    updated_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (task_id, chunk_index)
);

CREATE TABLE file_download_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id bigint NOT NULL REFERENCES file_assets(id),
    person_id bigint NOT NULL REFERENCES persons(id),
    device_id bigint REFERENCES user_devices(id),
    result_code varchar(64) NOT NULL,
    source_address inet,
    occurred_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_file_download_audit ON file_download_records(asset_id, occurred_at_utc DESC);

CREATE TABLE presence_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id bigint NOT NULL REFERENCES persons(id),
    device_id bigint REFERENCES user_devices(id),
    presence_state smallint NOT NULL,
    recorded_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at_utc timestamptz
);
CREATE INDEX idx_presence_person_time ON presence_history(person_id, recorded_at_utc DESC);

CREATE TABLE system_configs (
    config_key varchar(255) PRIMARY KEY,
    config_value jsonb NOT NULL,
    sensitive boolean NOT NULL DEFAULT false,
    revision bigint NOT NULL DEFAULT 1,
    updated_by_account_id bigint REFERENCES user_accounts(id),
    updated_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE operation_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_account_id bigint REFERENCES user_accounts(id),
    action varchar(128) NOT NULL,
    target_type varchar(64) NOT NULL,
    target_id varchar(128) NOT NULL,
    result_code varchar(64) NOT NULL,
    correlation_id uuid NOT NULL,
    source_address inet,
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    occurred_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_audit_time_action ON operation_audit_logs(occurred_at_utc DESC, action);

CREATE TABLE security_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    severity smallint NOT NULL,
    event_type varchar(128) NOT NULL,
    account_id bigint REFERENCES user_accounts(id),
    device_id bigint REFERENCES user_devices(id),
    correlation_id uuid,
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    handled boolean NOT NULL DEFAULT false,
    occurred_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_security_unhandled ON security_events(handled, severity, occurred_at_utc DESC);

CREATE TABLE client_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform varchar(64) NOT NULL,
    architecture varchar(64) NOT NULL,
    version varchar(64) NOT NULL,
    package_uri varchar(1024) NOT NULL,
    package_sm3 bytea NOT NULL,
    signature bytea NOT NULL,
    minimum_supported_version varchar(64) NOT NULL,
    mandatory boolean NOT NULL DEFAULT false,
    published_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (platform, architecture, version)
);

CREATE TABLE directory_import_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id bigint NOT NULL REFERENCES organizations(id),
    source_type varchar(32) NOT NULL,
    source_digest bytea NOT NULL,
    status smallint NOT NULL,
    created_by_account_id bigint NOT NULL REFERENCES user_accounts(id),
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at_utc timestamptz
);

CREATE TABLE directory_import_errors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint NOT NULL REFERENCES directory_import_tasks(id) ON DELETE CASCADE,
    row_number integer,
    field_name varchar(128),
    error_code varchar(64) NOT NULL,
    safe_message varchar(512) NOT NULL
);

INSERT INTO schema_migrations(version, description)
VALUES ('002', 'identity, communication, file and audit base schema')
ON CONFLICT (version) DO NOTHING;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO orglink_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO orglink_app;

COMMIT;

