BEGIN;

-- 迁移摘要由 orglink-migrator 写入；字段允许为空是为了兼容首次从 001/002 基线升级的数据库。
ALTER TABLE schema_migrations
    ADD COLUMN IF NOT EXISTS checksum_sha256 varchar(64);

-- pgcrypto 仅用于服务端口令校验和 UUID 生成；生产可替换为单位统一认证或密码机能力。
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE account_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_uuid uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    account_id bigint NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
    device_id bigint REFERENCES user_devices(id) ON DELETE CASCADE,
    token_digest bytea NOT NULL,
    source_address inet,
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at_utc timestamptz NOT NULL,
    revoked_at_utc timestamptz,
    last_seen_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (expires_at_utc > created_at_utc)
);
CREATE INDEX idx_account_sessions_active
    ON account_sessions(account_id, expires_at_utc)
    WHERE revoked_at_utc IS NULL;

-- 发件箱把“消息提交”和“等待投递”放在同一事务中，后续多节点路由可安全重放未完成事件。
CREATE TABLE message_outbox (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id bigint NOT NULL UNIQUE REFERENCES messages(id) ON DELETE CASCADE,
    recipient_person_id bigint NOT NULL REFERENCES persons(id),
    event_type varchar(64) NOT NULL,
    payload bytea NOT NULL,
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    available_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dispatched_at_utc timestamptz,
    last_error_code varchar(64) NOT NULL DEFAULT '',
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_message_outbox_pending
    ON message_outbox(available_at_utc, id)
    WHERE dispatched_at_utc IS NULL;

INSERT INTO schema_migrations(version, description)
VALUES ('003', 'runtime security and reliable message outbox')
ON CONFLICT (version) DO NOTHING;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO orglink_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO orglink_app;

COMMIT;
