BEGIN;

-- 文件资产正文进入 MinIO 后，PostgreSQL 只保存对象定位与完整性元数据；旧版 SM3 列改为可空，
-- 避免尚未接入合规密码模块的节点把 SHA-256 冒充为 SM3。sha256_digest 仍是当前上传必填校验值。
ALTER TABLE file_assets ALTER COLUMN sm3_digest DROP NOT NULL;
ALTER TABLE file_assets ADD COLUMN IF NOT EXISTS object_etag varchar(128);

-- 同一文件资产只能产生一条完成态文件消息，数据库唯一约束是重试幂等的最终边界。
ALTER TABLE file_transfer_tasks
    ADD COLUMN IF NOT EXISTS message_id bigint REFERENCES messages(id),
    ADD COLUMN IF NOT EXISTS client_message_id uuid;
CREATE UNIQUE INDEX IF NOT EXISTS uq_file_transfer_client_message
    ON file_transfer_tasks(initiator_person_id, client_message_id)
    WHERE client_message_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_file_transfer_completed_message
    ON file_transfer_tasks(asset_id) WHERE message_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_file_transfer_conversation_asset
    ON file_transfer_tasks(conversation_id, asset_id);

-- 会议房间只保存业务会话与 LiveKit 房间的映射，API Secret 和参与者 JWT 永不落库。
CREATE TABLE IF NOT EXISTS conference_rooms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conference_uuid uuid NOT NULL UNIQUE,
    conversation_id bigint NOT NULL REFERENCES conversations(id),
    provider varchar(32) NOT NULL DEFAULT 'livekit',
    room_name varchar(128) NOT NULL UNIQUE,
    created_by_person_id bigint NOT NULL REFERENCES persons(id),
    status smallint NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at_utc timestamptz NOT NULL,
    ended_at_utc timestamptz
);
CREATE INDEX IF NOT EXISTS idx_conference_rooms_active
    ON conference_rooms(conversation_id, expires_at_utc DESC)
    WHERE status = 1 AND ended_at_utc IS NULL;

-- 参与记录用于审计和界面“最近协作”，重复加入同一会议只刷新最后加入时间。
CREATE TABLE IF NOT EXISTS conference_participants (
    conference_id bigint NOT NULL REFERENCES conference_rooms(id) ON DELETE CASCADE,
    person_id bigint NOT NULL REFERENCES persons(id),
    joined_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at_utc timestamptz,
    PRIMARY KEY (conference_id, person_id)
);
CREATE INDEX IF NOT EXISTS idx_conference_participants_person
    ON conference_participants(person_id, joined_at_utc DESC);

INSERT INTO schema_migrations(version, description)
VALUES ('005', 'message center file object metadata and LiveKit conference records')
ON CONFLICT (version) DO NOTHING;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO orglink_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO orglink_app;

COMMIT;
