BEGIN;

-- 每名人员保存一份完整设置快照；revision 用于多个客户端之间的乐观并发控制。
CREATE TABLE user_settings (
    person_id bigint PRIMARY KEY REFERENCES persons(id) ON DELETE CASCADE,
    revision bigint NOT NULL DEFAULT 1 CHECK (revision > 0),
    two_factor_enabled boolean NOT NULL DEFAULT false,
    startup_enabled boolean NOT NULL DEFAULT true,
    auto_login_enabled boolean NOT NULL DEFAULT false,
    auto_lock_minutes integer NOT NULL DEFAULT 10 CHECK (auto_lock_minutes BETWEEN 1 AND 1440),
    chat_watermark_enabled boolean NOT NULL DEFAULT true,
    screenshot_protection_enabled boolean NOT NULL DEFAULT false,
    download_path varchar(1024) NOT NULL DEFAULT 'Downloads',
    language varchar(32) NOT NULL DEFAULT 'zh-CN' CHECK (language IN ('zh-CN', 'en-US')),
    theme varchar(32) NOT NULL DEFAULT 'system' CHECK (theme IN ('system', 'light', 'dark')),
    storage_quota_bytes bigint NOT NULL DEFAULT 5368709120 CHECK (storage_quota_bytes > 0),
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 设置变更事件保留前后快照，便于安全审计和排查多端覆盖，不保存口令或本地文件内容。
CREATE TABLE user_setting_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id bigint NOT NULL REFERENCES persons(id) ON DELETE CASCADE,
    revision bigint NOT NULL CHECK (revision > 0),
    action smallint NOT NULL CHECK (action IN (1, 2)),
    previous_settings jsonb NOT NULL,
    current_settings jsonb NOT NULL,
    occurred_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_user_setting_events_person_time
    ON user_setting_events(person_id, occurred_at_utc DESC);

-- 为现有账号幂等创建默认设置；后续新账号由首次查询时补建，避免修改认证事务边界。
INSERT INTO user_settings(person_id)
SELECT person_id FROM user_accounts
ON CONFLICT (person_id) DO NOTHING;

GRANT SELECT, INSERT, UPDATE ON user_settings TO orglink_app;
GRANT SELECT, INSERT ON user_setting_events TO orglink_app;
GRANT USAGE, SELECT ON SEQUENCE user_setting_events_id_seq TO orglink_app;

INSERT INTO schema_migrations(version, description)
VALUES ('009', 'per-user settings snapshots and audit events')
ON CONFLICT (version) DO NOTHING;

COMMIT;
