BEGIN;

-- 办公地点与直属上级属于组织主数据；允许为空，避免为历史人员伪造信息。
ALTER TABLE persons
    ADD COLUMN IF NOT EXISTS office_location varchar(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS manager_person_id bigint REFERENCES persons(id);

CREATE INDEX IF NOT EXISTS idx_persons_manager ON persons(manager_person_id);

-- 联系人偏好按“当前人员 + 联系人”隔离；revision 用于阻止多客户端静默覆盖标签和备注。
CREATE TABLE IF NOT EXISTS contact_profiles (
    owner_person_id bigint NOT NULL REFERENCES persons(id) ON DELETE CASCADE,
    contact_person_id bigint NOT NULL REFERENCES persons(id) ON DELETE CASCADE,
    favorite boolean NOT NULL DEFAULT false,
    tags text[] NOT NULL DEFAULT '{}',
    note varchar(512) NOT NULL DEFAULT '',
    revision bigint NOT NULL DEFAULT 1 CHECK (revision > 0),
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (owner_person_id, contact_person_id),
    CHECK (owner_person_id <> contact_person_id),
    CHECK (cardinality(tags) <= 12)
);

CREATE INDEX IF NOT EXISTS idx_contact_profiles_favorite
    ON contact_profiles(owner_person_id, updated_at_utc DESC)
    WHERE favorite;

-- 兼容早期 favorite_contacts 数据；新代码只写 contact_profiles，旧表暂时保留供回滚版本读取。
INSERT INTO contact_profiles(owner_person_id, contact_person_id, favorite)
SELECT owner_person_id, contact_person_id, true
FROM favorite_contacts
ON CONFLICT (owner_person_id, contact_person_id)
DO UPDATE SET favorite=true, updated_at_utc=CURRENT_TIMESTAMP;

-- 最近联系人由服务端在单聊成功打开后更新，客户端不能提交时间戳或次数。
CREATE TABLE IF NOT EXISTS contact_interactions (
    owner_person_id bigint NOT NULL REFERENCES persons(id) ON DELETE CASCADE,
    contact_person_id bigint NOT NULL REFERENCES persons(id) ON DELETE CASCADE,
    interaction_count bigint NOT NULL DEFAULT 1 CHECK (interaction_count > 0),
    last_interaction_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (owner_person_id, contact_person_id),
    CHECK (owner_person_id <> contact_person_id)
);

CREATE INDEX IF NOT EXISTS idx_contact_interactions_recent
    ON contact_interactions(owner_person_id, last_interaction_at_utc DESC);

-- 审计只保存个人偏好前后快照，不复制手机号、邮箱等组织敏感字段。
CREATE TABLE IF NOT EXISTS contact_preference_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_person_id bigint NOT NULL REFERENCES persons(id) ON DELETE CASCADE,
    contact_person_id bigint NOT NULL REFERENCES persons(id) ON DELETE CASCADE,
    revision bigint NOT NULL CHECK (revision > 0),
    previous_profile jsonb NOT NULL,
    current_profile jsonb NOT NULL,
    occurred_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_contact_preference_events_owner_time
    ON contact_preference_events(owner_person_id, occurred_at_utc DESC);

INSERT INTO schema_migrations(version, description)
VALUES ('010', 'contact center preferences recents and organization detail fields')
ON CONFLICT (version) DO NOTHING;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO orglink_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO orglink_app;

COMMIT;
