BEGIN;

-- 文件中心允许上传不隶属于聊天会话的个人文件；会话附件仍必须保留 conversation_id，
-- 独立文件则在完成阶段关联 file_document_id，二者不能同时为空。
ALTER TABLE file_transfer_tasks ALTER COLUMN conversation_id DROP NOT NULL;

/**
 * 文件夹只保存逻辑层级，不直接映射 MinIO 前缀；对象键始终由服务端随机生成，
 * 避免重命名或移动文件夹时批量复制对象，也阻止客户端利用路径穿越控制存储位置。
 */
CREATE TABLE IF NOT EXISTS file_folders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folder_uuid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    owner_person_id bigint NOT NULL REFERENCES persons(id),
    parent_folder_id bigint REFERENCES file_folders(id),
    name varchar(255) NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 255),
    revision bigint NOT NULL DEFAULT 1 CHECK (revision > 0),
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at_utc timestamptz,
    CHECK (parent_folder_id IS NULL OR parent_folder_id <> id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_file_folders_root_name
    ON file_folders(owner_person_id, lower(name))
    WHERE parent_folder_id IS NULL AND deleted_at_utc IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_file_folders_parent_name
    ON file_folders(owner_person_id, parent_folder_id, lower(name))
    WHERE parent_folder_id IS NOT NULL AND deleted_at_utc IS NULL;
CREATE INDEX IF NOT EXISTS idx_file_folders_owner_parent
    ON file_folders(owner_person_id, parent_folder_id, updated_at_utc DESC);

/**
 * file_documents 是用户可见的逻辑文件，file_assets 是不可变正文版本。
 * current_asset_id 指向当前版本；收藏、回收站和 revision 均属于逻辑文件，不能写回物理对象。
 */
CREATE TABLE IF NOT EXISTS file_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_uuid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    owner_person_id bigint NOT NULL REFERENCES persons(id),
    folder_id bigint REFERENCES file_folders(id),
    current_asset_id bigint NOT NULL REFERENCES file_assets(id),
    display_name varchar(512) NOT NULL CHECK (length(btrim(display_name)) BETWEEN 1 AND 512),
    media_category smallint NOT NULL DEFAULT 7 CHECK (media_category BETWEEN 1 AND 7),
    favorite boolean NOT NULL DEFAULT false,
    revision bigint NOT NULL DEFAULT 1 CHECK (revision > 0),
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_accessed_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at_utc timestamptz
);
CREATE INDEX IF NOT EXISTS idx_file_documents_owner_active
    ON file_documents(owner_person_id, updated_at_utc DESC)
    WHERE deleted_at_utc IS NULL;
CREATE INDEX IF NOT EXISTS idx_file_documents_owner_deleted
    ON file_documents(owner_person_id, deleted_at_utc DESC)
    WHERE deleted_at_utc IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_file_documents_folder
    ON file_documents(folder_id, updated_at_utc DESC)
    WHERE deleted_at_utc IS NULL;

-- 每个版本绑定一个不可变 file_asset；当前版本仍通过 file_documents.current_asset_id 快速读取。
CREATE TABLE IF NOT EXISTS file_document_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id bigint NOT NULL REFERENCES file_documents(id) ON DELETE CASCADE,
    version_number integer NOT NULL CHECK (version_number > 0),
    asset_id bigint NOT NULL REFERENCES file_assets(id),
    created_by_person_id bigint NOT NULL REFERENCES persons(id),
    change_note varchar(512) NOT NULL DEFAULT '',
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(document_id, version_number),
    UNIQUE(asset_id)
);
CREATE INDEX IF NOT EXISTS idx_file_document_versions_document
    ON file_document_versions(document_id, version_number DESC);

-- 共享记录支持人员和群组两种受体；撤销采用时间戳保留审计证据，权限 1/2 表示查看/可编辑。
CREATE TABLE IF NOT EXISTS file_document_shares (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id bigint NOT NULL REFERENCES file_documents(id) ON DELETE CASCADE,
    grantee_person_id bigint REFERENCES persons(id),
    grantee_group_id bigint REFERENCES chat_groups(id),
    permission smallint NOT NULL CHECK (permission IN (1, 2)),
    granted_by_person_id bigint NOT NULL REFERENCES persons(id),
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at_utc timestamptz,
    CHECK ((grantee_person_id IS NOT NULL)::integer + (grantee_group_id IS NOT NULL)::integer = 1)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_file_document_person_share
    ON file_document_shares(document_id, grantee_person_id)
    WHERE grantee_person_id IS NOT NULL AND revoked_at_utc IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_file_document_group_share
    ON file_document_shares(document_id, grantee_group_id)
    WHERE grantee_group_id IS NOT NULL AND revoked_at_utc IS NULL;
CREATE INDEX IF NOT EXISTS idx_file_document_shares_person
    ON file_document_shares(grantee_person_id, created_at_utc DESC)
    WHERE revoked_at_utc IS NULL;
CREATE INDEX IF NOT EXISTS idx_file_document_shares_group
    ON file_document_shares(grantee_group_id, created_at_utc DESC)
    WHERE revoked_at_utc IS NULL;

-- 事件只保存文件中心元数据前后状态，不记录对象键、摘要正文或任何 MinIO 凭据。
CREATE TABLE IF NOT EXISTS file_document_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id bigint NOT NULL REFERENCES file_documents(id) ON DELETE CASCADE,
    actor_person_id bigint NOT NULL REFERENCES persons(id),
    action varchar(32) NOT NULL,
    previous_state jsonb NOT NULL DEFAULT '{}'::jsonb,
    current_state jsonb NOT NULL DEFAULT '{}'::jsonb,
    occurred_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_file_document_events_document
    ON file_document_events(document_id, occurred_at_utc DESC);

ALTER TABLE file_transfer_tasks
    ADD COLUMN IF NOT EXISTS file_document_id bigint REFERENCES file_documents(id);
CREATE INDEX IF NOT EXISTS idx_file_transfer_document
    ON file_transfer_tasks(file_document_id, updated_at_utc DESC)
    WHERE file_document_id IS NOT NULL;

-- 已有任务全部属于会话附件；新约束保证未来独立上传最终至少关联一种业务载体。
ALTER TABLE file_transfer_tasks DROP CONSTRAINT IF EXISTS ck_file_transfer_business_target;
ALTER TABLE file_transfer_tasks ADD CONSTRAINT ck_file_transfer_business_target
    CHECK (conversation_id IS NOT NULL OR file_document_id IS NOT NULL OR status IN (1, 3));

INSERT INTO schema_migrations(version, description)
VALUES ('011', 'file center folders documents versions shares and audit')
ON CONFLICT (version) DO NOTHING;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO orglink_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO orglink_app;

COMMIT;
