BEGIN;

/**
 * calendar_events 保存组织内日程主数据。
 * 可见性不由 calendar_kind 决定，而由 organizer_person_id 和 calendar_event_participants 共同决定；
 * 取消采用状态字段保留审计证据，revision 用于阻止多端静默覆盖。
 */
CREATE TABLE IF NOT EXISTS calendar_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_uuid uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    organization_id bigint NOT NULL REFERENCES organizations(id),
    organizer_person_id bigint NOT NULL REFERENCES persons(id),
    calendar_kind smallint NOT NULL CHECK (calendar_kind BETWEEN 1 AND 3),
    calendar_name varchar(128) NOT NULL CHECK (length(btrim(calendar_name)) BETWEEN 1 AND 128),
    color varchar(16) NOT NULL DEFAULT '#1677FF' CHECK (color ~ '^#[0-9A-Fa-f]{6}$'),
    title varchar(255) NOT NULL CHECK (length(btrim(title)) BETWEEN 1 AND 255),
    description varchar(2048) NOT NULL DEFAULT '',
    location varchar(512) NOT NULL DEFAULT '',
    starts_at_utc timestamptz NOT NULL,
    ends_at_utc timestamptz NOT NULL,
    all_day boolean NOT NULL DEFAULT false,
    meeting_number varchar(64),
    reminder_minutes integer NOT NULL DEFAULT 15 CHECK (reminder_minutes BETWEEN 0 AND 10080),
    status smallint NOT NULL DEFAULT 0 CHECK (status IN (0, 1)),
    revision bigint NOT NULL DEFAULT 1 CHECK (revision > 0),
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (ends_at_utc > starts_at_utc)
);
CREATE INDEX IF NOT EXISTS idx_calendar_events_organization_range
    ON calendar_events(organization_id, starts_at_utc, ends_at_utc);
CREATE INDEX IF NOT EXISTS idx_calendar_events_organizer
    ON calendar_events(organizer_person_id, starts_at_utc DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_calendar_events_meeting_number
    ON calendar_events(organization_id, meeting_number)
    WHERE meeting_number IS NOT NULL;

-- 参与人记录是日程读取权限的来源；创建者也以 Accepted 身份写入，简化一致的参与人投影。
CREATE TABLE IF NOT EXISTS calendar_event_participants (
    event_id bigint NOT NULL REFERENCES calendar_events(id) ON DELETE CASCADE,
    person_id bigint NOT NULL REFERENCES persons(id),
    participation_status smallint NOT NULL DEFAULT 0 CHECK (participation_status BETWEEN 0 AND 2),
    added_by_person_id bigint NOT NULL REFERENCES persons(id),
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (event_id, person_id)
);
CREATE INDEX IF NOT EXISTS idx_calendar_participants_person
    ON calendar_event_participants(person_id, event_id);

-- 审计事件只记录业务字段快照，不保存认证信息、网络地址或其他秘密。
CREATE TABLE IF NOT EXISTS calendar_event_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint NOT NULL REFERENCES calendar_events(id) ON DELETE CASCADE,
    actor_person_id bigint NOT NULL REFERENCES persons(id),
    action varchar(32) NOT NULL CHECK (action IN ('create', 'update', 'cancel')),
    previous_state jsonb NOT NULL DEFAULT '{}'::jsonb,
    current_state jsonb NOT NULL DEFAULT '{}'::jsonb,
    occurred_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_calendar_event_audit_event
    ON calendar_event_audit(event_id, occurred_at_utc DESC);

-- 由迁移文件先建立版本行，迁移器随后以文件 SHA-256 回填校验和，保证重复部署可审计且不会重复建表。
INSERT INTO schema_migrations(version, description)
VALUES ('012', 'calendar center events participants and audit')
ON CONFLICT (version) DO NOTHING;

GRANT SELECT, INSERT, UPDATE, DELETE ON calendar_events TO orglink_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON calendar_event_participants TO orglink_app;
GRANT SELECT, INSERT ON calendar_event_audit TO orglink_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO orglink_app;

COMMIT;
