BEGIN;

-- Web 管理端对组织和人员采用乐观锁；版本号用于拒绝覆盖其他管理员刚刚完成的修改。
ALTER TABLE departments
    ADD COLUMN IF NOT EXISTS revision bigint NOT NULL DEFAULT 1 CHECK (revision > 0);
ALTER TABLE persons
    ADD COLUMN IF NOT EXISTS revision bigint NOT NULL DEFAULT 1 CHECK (revision > 0);

/**
 * 管理角色与普通即时通信账号分离。角色只授予已有账号，避免把登录成功等同于管理授权。
 * org_admin 仅能管理自身组织，super_admin 保留跨组织扩展能力，但当前接口仍默认限制在管理员所属组织。
 */
CREATE TABLE IF NOT EXISTS administrator_roles (
    account_id bigint PRIMARY KEY REFERENCES user_accounts(id) ON DELETE CASCADE,
    role_name varchar(32) NOT NULL CHECK (role_name IN ('super_admin', 'org_admin')),
    enabled boolean NOT NULL DEFAULT true,
    granted_by_account_id bigint REFERENCES user_accounts(id),
    granted_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

/**
 * 浏览器会话只保存随机令牌与 CSRF 令牌的 SHA-256 摘要；Cookie 原文和口令不会写入数据库或日志。
 * 会话到期或注销后保留撤销时间，以便安全审计和故障排查。
 */
CREATE TABLE IF NOT EXISTS administrator_web_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_uuid uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    account_id bigint NOT NULL REFERENCES user_accounts(id) ON DELETE CASCADE,
    token_digest bytea NOT NULL UNIQUE,
    csrf_digest bytea NOT NULL,
    source_address inet,
    user_agent_digest bytea,
    created_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at_utc timestamptz NOT NULL,
    last_seen_at_utc timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at_utc timestamptz,
    CHECK (expires_at_utc > created_at_utc)
);
CREATE INDEX IF NOT EXISTS idx_administrator_web_sessions_active
    ON administrator_web_sessions(account_id, expires_at_utc)
    WHERE revoked_at_utc IS NULL;

-- 首装管理员通过固定工号识别；重复迁移不会扩大其他账号权限。
INSERT INTO administrator_roles(account_id, role_name)
SELECT ua.id, 'super_admin'
FROM user_accounts ua
JOIN persons p ON p.id = ua.person_id
WHERE p.employee_number = 'ADMIN-0001'
ON CONFLICT (account_id) DO NOTHING;

-- 兼容已经存在的组织：确保后续每次管理变更都有连续的组织修订号。
INSERT INTO organization_revisions(organization_id, current_revision)
SELECT id, GREATEST(revision, 1) FROM organizations
ON CONFLICT (organization_id) DO NOTHING;

INSERT INTO schema_migrations(version, description)
VALUES ('021', 'angular web administration roles sessions and optimistic revisions')
ON CONFLICT (version) DO NOTHING;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO orglink_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO orglink_app;

COMMIT;
